budzetBozy/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
 
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainapp.urls')),
]
 
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

mainapp/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^raport$', views.raport, name='raport'),
    url(r'^raportAll$', views.raportAll, name='raportAll'),
    url(r'^dodanie_transakcji$', views.dodanie_transakcji,name='dodanie_transakcji'),
    path('usuwanie_transakcji/<int:id>', views.usuwanie_transakcji,name='usuwanie_transakcji'),
    url(r'^dodanie_kategorii$', views.dodanie_kategorii, name='dodanie_kategorii'),
    path('usuwanie_kategorii/<int:id>',views.usuwanie_kategorii, name='usuwanie_kategorii'),
    url(r'^dodanie_konta$', views.dodanie_konta, name='dodanie_konta'),
    path('usuwanie_konta/<int:id>', views.usuwanie_konta,name='usuwanie_konta'),
    url(r'^dodanie_zlecenia_stalego$', views.dodanie_zlecenia_stalego, name='dodanie_zlecenia_stalego'),
    path('usuwanie_zlecenia_stalego/<int:id>', views.usuwanie_zlecenia_stalego,name='usuwanie_zlecenia_stalego'),
    path('konto/<int:id>',views.konto_details, name='konto_details'),
    path('raport_pdf',views.raport_pdf, name='raport_pdf'),
    url(r'^zlecenia_stale$', views.zlecenia_stale, name='zlecenia_stale'),
]

mainapp/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from decimal import Decimal

class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name="użytkownik")
    name = models.CharField("nazwa", max_length=25)
    balance = models.DecimalField("saldo", max_digits=100, decimal_places=2,default=Decimal('0.00'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "konto"
        verbose_name_plural = "konta"


class Currency(models.Model):
    id = models.CharField(max_length=3, primary_key=True)
    rate = models.DecimalField("kurs", max_digits=5, decimal_places=4)

    def __str__(self):
        return self.id

    class Meta:
        verbose_name = "waluta"
        verbose_name_plural = "waluty"


class Category(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    name = models.CharField("nazwa", max_length=100)
    
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = "kategoria"
        verbose_name_plural = "kategorie"

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    title = models.CharField("tytuł",max_length=50, default='')
    date = models.DateField("data", default=date.today)
    amount = models.DecimalField("kwota", max_digits=100, decimal_places=2)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, verbose_name="waluta")
    categories = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name="kategoria")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-date']
        verbose_name = "transakcja"
        verbose_name_plural = "transakcje"


class Permission(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    owner = models.BooleanField("właściciel", default=True)

    class Meta:
        verbose_name = "uprawnienia"

class StandingOrder(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    account = models.ForeignKey(Account, on_delete=models.CASCADE) 
    title = models.CharField("tytuł", max_length=30, default='') 
    amount = models.DecimalField("kwota", max_digits=100, decimal_places=2) 
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, verbose_name="waluta") 
    categories = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name="kategoria")
    next_date = models.DateField("data następnego wykonania", default=date.today) 
    frequency = models.IntegerField("częstotliwość") 
 
    def __str__(self):
        return self.title
        
    class Meta: 
        ordering = ['next_date']
        verbose_name = "zlecenie stałe"
        verbose_name_plural = "zlecenia stałe" 

mainapp/forms.py
from django import forms
from .models import Transaction, Category, StandingOrder, Account
from datetimewidget.widgets import DateWidget



class TransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        #widgets = {'date': DateWidget(
        #    attrs={'id': 'date'}, bootstrap_version=3, options={'todayHighlight': True})}
        fields = ('title', 'amount', 'currency', 'date', 'categories',)



class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)


class StandingOrderForm(forms.ModelForm):
    class Meta:
        model = StandingOrder
        fields = ('title', 'amount', 'currency',
                  'categories', 'frequency', 'next_date',)


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('name',)

mainapp/views.py
from django.shortcuts import render, redirect
from django.conf import settings
 
# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import *
from .forms import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa
import datetime

from django.views.generic import ListView
 

def index(request):
    if request.user.is_authenticated:
        accounts = Account.objects.filter(user = request.user).values()
        request.session['accounts'] = list(accounts)
        for i in request.session['accounts']:
            i['balance'] = str(i['balance'])
        return render(request,'index.html')
    else:
        return render(request,'registration/login.html')

@login_required
def raport(request):
    if request.session.has_key('current_account'):
        transactions = Transaction.objects.filter(user = request.user,account = request.session.get('current_account')['id']).values()
        for trans in transactions:
            trans['account_id'] = Account.objects.get(pk=trans['account_id']).name
            trans['categories_id'] = Category.objects.get(pk=trans['categories_id']).name
        context = {'transactions' : list(transactions)}
        return render(request,'raport.html', context)
    else:
        return redirect('index')

@login_required
def raportAll(request):
    transactions = Transaction.objects.filter(user = request.user).values()
    for trans in transactions:
        trans['account_id'] = Account.objects.get(pk=trans['account_id']).name
        trans['categories_id'] = Category.objects.get(pk=trans['categories_id']).name
    context = {'transactions': list(transactions)}
    return render(request,'raportAll.html', context)

@login_required
def zlecenia_stale(request):
    standOrds = StandingOrder.objects.filter(user = request.user).values()
    for stor in standOrds:
        stor['account_id'] = Account.objects.get(pk=stor['account_id']).name
        stor['categories_id'] = Category.objects.get(pk=stor['categories_id']).name
    context = {'standOrds': list(standOrds)}
    return render(request,'zlecenia-stale.html', context)

@login_required
def dodanie_transakcji(request):
    if request.method == "POST":
        form = TransactionForm(request.POST)
        if form.is_valid():
            trans = form.save(commit=False)
            if request.POST['type'] == "Wydatek":
                trans.amount = trans.amount * (-1)
            trans.user = request.user
            trans.account = Account.objects.get(pk=request.session.get('current_account')['id'])
            trans.save()
            acc = trans.account
            acc.balance += trans.amount*Currency.objects.get(pk = trans.currency).rate
            acc.save()
            accounts = Account.objects.filter(user = request.user).values()
            request.session['accounts'] = list(accounts)
            for i in request.session['accounts']:
                i['balance'] = str(i['balance'])

        return redirect('raport')
    else:
        form = TransactionForm()
        return render(request, 'dodanie-transakcji.html', {'form':form})
@login_required
def usuwanie_transakcji(request,id):
    trans = Transaction.objects.get(pk=id)
    acc = trans.account
    acc.balance -= trans.amount*Currency.objects.get(pk = trans.currency).rate
    acc.save()
    trans.delete()

    accounts = Account.objects.filter(user = request.user).values()
    request.session['accounts'] = list(accounts)
    for i in request.session['accounts']:
        i['balance'] = str(i['balance'])

    return redirect('raport')

def usuwanie_zlecenia_stalego(request,id):
    stor = StandingOrder.objects.get(pk=id)
    stor.delete()

    return redirect('zlecenia_stale')

@login_required
def dodanie_zlecenia_stalego(request):
    if request.session.has_key('current_account'): 
        if request.method == "POST": 
            form = StandingOrderForm(request.POST)
            if form.is_valid():
                stor = form.save(commit=False)
                if request.POST['type'] == "Wydatek":
                    stor.amount = stor.amount * (-1)
                stor.user = request.user
                stor.account = Account.objects.get(pk=request.session.get('current_account')['id'])
                stor.save()
            return redirect('zlecenia_stale') 
        else: 
            form = StandingOrderForm() 
            return render(request, 'dodanie-zlecenia-stalego.html', {'form':form})
    else:
        redirect('index') 

@login_required 
def dodanie_kategorii(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            cat = form.save(commit=False)
            cat.account = Account.objects.get(pk=request.session.get('current_account')['id'])
            cat.save()
        return redirect('index')
    else:
        form = CategoryForm()
        return render(request, 'dodanie-kategorii.html', {'form':form})

@login_required
def usuwanie_kategorii(request,id):
    cat = Category.objects.get(pk=id)
    cat.delete()

    accounts = Account.objects.filter(user = request.user).values()
    request.session['accounts'] = list(accounts)
    for i in request.session['accounts']:
        i['balance'] = str(i['balance'])

    return redirect('raport')

@login_required
def dodanie_konta(request):
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            acc = form.save(commit=False)
            acc.user = request.user
            acc.balance = 0
            acc.save()
            permission = Permission(user = request.user, account = acc, owner = True)
            permission.save()
        return redirect('index')
    else:
        form = AccountForm()
        return render(request, 'dodanie-konta.html', {'form':form})

@login_required
def usuwanie_konta(request,id):
    acc = Account.objects.get(pk=id)
    acc.delete()

    del request.session['current_account']
    accounts = Account.objects.filter(user = request.user).values()
    request.session['accounts'] = list(accounts)
    for i in request.session['accounts']:
        i['balance'] = str(i['balance'])

    return redirect('raport')

@login_required
def konto_details(request, id):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            cat = form.save(commit=False)
            cat.account = Account.objects.get(pk=request.session.get('current_account')['id']) 
            cat.save()
        return redirect('index')
    else:
        form = CategoryForm()
        permissions = Permission.objects.filter(account = id).values()
        categories = Category.objects.filter(account = id).values()
        acc = Account.objects.get(pk=id)
        for perm in permissions:
            perm['user_id'] = User.objects.get(pk=perm['user_id']).username
        for account in request.session['accounts']:
            if account['id'] == id:
                request.session['current_account'] = account
        context = {'permissions' : list(permissions), 'current_account':acc, 'form':form, 'categories':list(categories)} 
        return render(request,'konto_details.html', context)

@login_required
def raport_pdf(request):
    if request.session.has_key('current_account'):
        transactions = Transaction.objects.filter(user = request.user,account = request.session.get('current_account')['id']).values()
        for trans in transactions:
            trans['user_id'] = User.objects.get(pk=trans['user_id']).username
            trans['categories_id'] = Category.objects.get(pk=trans['categories_id']).name
        date  = datetime.date.today()
        context = {'request' : request, 'transactions' : list(transactions), 'date': date}
        return PdfRender.render('raport-pdf.html', params=context)
    else:
        return redirect('index')
        

# def render_pdf_view(request):
#     template_path = 'raport.html'
#     # context = {'myvar': 'this is your template context'}
#     # Create a Django response object, and specify content_type as pdf
#     response = HttpResponse(content_type='application/pdf')
#     response['Content-Disposition'] = 'attachment; filename="report.pdf"'
#     # find the template and render it.
#     template = get_template(template_path)
#     html = template.render(Context(context))

#     # create a pdf
#     pisaStatus = pisa.CreatePDF(
#        html, dest=response, link_callback=link_callback)
#     if pisaStatus.err:
#        return HttpResponse('We had some errors <pre>' + html + '</pre>')
#     return response

def anonymous_required(view_function, redirect_to = None):
    return AnonymousRequired(view_function, redirect_to)
 
class AnonymousRequired(object):
    def __init__(self, view_function, redirect_to):
        if redirect_to is None:
            redirect_to = settings.LOGIN_REDIRECT_URL
        self.view_function = view_function
        self.redirect_to = redirect_to
 
    def __call__(self, request, *args, **kwargs):
        if request.user is not None and request.user.is_authenticated:
            return HttpResponseRedirect(self.redirect_to)
        return self.view_function(request, *args, **kwargs)

class PdfRender:

    @staticmethod
    def render(path: str, params: dict):
        template = get_template(path)
        html = template.render(params)
        response = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            return HttpResponse(response.getvalue(), content_type='application/pdf')
        else:
            return HttpResponse("Error Rendering PDF", status=400)

# @anonymous_required
# def register(request):
#     register_form = RegistrationForm(request.POST or None,
#         initial={

mainapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">

<head>
	<meta charset="utf-8">
	<title>{% block title %}Baza{% endblock %}</title>
	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'base.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'breadcrumb.css' %}" type="text/css">
	{% if form %}
    {{ form.media }}
    {% endif %}

</head>

</head>

<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">Budżet domowy</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
				<li>
					<a>
						<span class="glyphicon glyphicon-user"></span> {{ user.get_username }}</a>
				</li>
				<li>
					<a href="{% url 'logout'%}?next={{request.path}}">
						<span class="glyphicon glyphicon-log-out"></span> Logout</a>
				</li>
				{% else %}
				<li>
					<a href="{% url 'login'%}?next={{request.path}}">
						<span class="glyphicon glyphicon-log-in"></span> Login</a>
				</li>
				{% endif %}
			</ul>
		</div>
	</nav>

	<div class="row-offcanvas row-offcanvas-left">
		<div id="sidebar" class="sidebar-offcanvas navbar-inverse">
			<div class="col-md-12 well well-sm">
				{% if user.get_full_name  %}
				<h4>
					Witaj, {{ user.get_full_name }}!
				</h4>
				{% else %}
				<h4>
					Witaj!
				</h4>
				{% endif %}<br>
				<dl>
					<dt>
						Aktywna skarbonka:
					</dt>
					<dd>
						{% if request.session.current_account %} 
						{{ request.session.current_account.name }}
						{% else %}
						Nie wybrano
						{% endif %}
					</dd>
				</dl>
			</div>
			<div class="col-md-12">
				<ul class="nav nav-pills nav-stacked">
					<li class="dropdown">
						<a class="nav-item" href="#transactionsSubmenu" data-toggle="collapse" aria-expanded="false">Moje transakcje
						</a>
						<ul class="collapse nav nav-pills nav-stacked dropdown-container" id="transactionsSubmenu">
							<li>
								<a href="/raport">Transakcje skarbonki</a>
							</li>
							<li>
								<a href="/raportAll">Wszystkie transakcje</a>
							</li>
							<li>
								<a href="{% url 'dodanie_transakcji' %}">
									<span class="glyphicon glyphicon-plus"></span> Dodaj</a>
							</li>
						</ul>
					</li>
					<li class="dropdown">
						<a class="nav-item" href="#accountsSubmenu" data-toggle="collapse" aria-expanded="false">Moje konta
						</a>
						<ul class="collapse nav nav-pills nav-stacked dropdown-container" id="accountsSubmenu">
							{% for acc in request.session.accounts %}
							<li>
								<a href="/konto/{{ acc.id }}">{{ acc.name }}</a>
							</li>
							{% endfor %}
							<li>
								<a href="{% url 'dodanie_konta' %}">
									<span class="glyphicon glyphicon-plus"></span> Dodaj</a>
							</li>
						</ul>
					</li>
					<li class="nav-item">
						<a href="/zlecenia_stale">
							Zlecenia stałe</a>
					</li>
				</ul>
			</div>
		</div>
		<div id="main">
			<div class="container-fluid">
				{% block content %}"Baza"{% endblock %}
			</div>
		</div>
	</div>
</body>

</html>

mainapp/templates/dodanie-konta.html
{% extends "base.html" %} 
    {% block title %}
        Nowe konto | Budżet domowy
    {% endblock %} 
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'forms.css' %}" type="text/css"/>

<div id="breadcrumb-panel">
    <ol class="breadcrumb breadcrumb-arrow">
        <li>
            <a href="/">
                <i class="glyphicon glyphicon-home"></i>
            </a>
        </li>
        <li class="active"><span>Nowa skarbonka</span>
        </li>
    </ol>
</div>

<div class="main-container">
    <div class="container">
        <div id="form-wrapper" class="form-container">
            <form method="POST" class="account-form">{% csrf_token %} 
                <div class="form-group">
                    {{ form.name.errors }}
                    <label class="reg-lbl" for="{{ form.name.id_for_label }}">Nazwa: </label>
                    {{ form.name }}
                </div> 
                <button type="submit" class="save btn btn-default">Dodaj</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/dodanie-transakcji.html
{% extends "base.html" %} 
    {% block title %}
        Nowa transakcja | Budżet domowy
    {% endblock %}  
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'forms.css' %}" type="text/css"/>

<div id="breadcrumb-panel">
    <ol class="breadcrumb breadcrumb-arrow">
        <li>
            <a href="/">
                <i class="glyphicon glyphicon-home"></i>
            </a>
        </li>
        <li><a href="/raport">Moje transakcje</a>
        </li>
        <li class="active"><span>Nowa transakcja</span>
        </li>
    </ol>
</div>

<div class="main-container">
    <div class="container">
        <div id="form-wrapper" class="form-container">
            <form method="POST" class="transaction-form">{% csrf_token %} 
                <div class="form-group">
                    {{ form.title.errors }}
                    <label class="reg-lbl" for="{{ form.title.id_for_label }}">Tytuł: </label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    {{ form.amount.errors }}
                    <label class="reg-lbl" for="{{ form.amount.id_for_label }}">Kwota: </label>
                    <input class="form-control" id="id_amount" type="number" name="amount" required="" step="0.01"/> 
                </div>
                <div class="form-group">
                     {{ form.currency.errors }}
                    <label class="reg-lbl" for="{{ form.currency.id_for_label }}">Waluta: </label>
                    {{ form.currency }}
                </div>
                <div class="form-group">
                    {{ form.categories.errors }}
                    <label class="reg-lbl" for="{{ form.categories.id_for_label }}">Kategoria: </label>
                    {{ form.categories }}
                </div> 
                <div class="form-group">
                    {{ form.date.errors }}
                    <label class="reg-lbl" for="{{ form.date.id_for_label }}">Data: </label>
                    {{ form.date }}
                </div>
                <div class="form-group">
                    <label class="reg-lbl" for="type">Typ transakcji:</label>
                    <select class="form-control" value="{{ type }}" name="type" id="type">
                        <option>Wydatek</option>
                        <option>Przychód</option>
                    </select>
                </div>
                <input type="hidden" name="next" value="{{ request.path }}">
                <button type="submit" class="save btn btn-default">Dodaj</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/dodanie-zlecenia-stalego.html
{% extends "base.html" %} 
    {% block title %}Nowe zlecenie stałe | Budżet domowy{% endblock %} 
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'forms.css' %}" type="text/css"/>

<div id="breadcrumb-panel">
    <ol class="breadcrumb breadcrumb-arrow">
        <li>
            <a href="/">
                <i class="glyphicon glyphicon-home"></i>
            </a>
        </li>
        <li class="active"><span>Nowe zlecenie stałe</span>
        </li>
    </ol>
</div>

<div class="main-container">
        <div class="container">
            <div id="form-wrapper" class="form-container">
                <form method="POST" class="standing-order-form">{% csrf_token %} 
                    <div class="form-group">
                        {{ form.title.errors }}
                        <label class="reg-lbl" for="{{ form.title.id_for_label }}">Tytuł: </label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        {{ form.amount.errors }}
                        <label class="reg-lbl" for="{{ form.amount.id_for_label }}">Kwota: </label>
                        <input class="form-control" id="id_amount" type="number" name="amount" required="" min="0" step="0.01"/> 
                    </div>
                    <div class="form-group">
                         {{ form.currency.errors }}
                        <label class="reg-lbl" for="{{ form.currency.id_for_label }}">Waluta: </label>
                        {{ form.currency }}
                    </div>
                    <div class="form-group">
                        {{ form.categories.errors }}
                        <label class="reg-lbl" for="{{ form.categories.id_for_label }}">Kategoria: </label>
                        {{ form.categories }}
                    </div>         
                    <div class="form-group">
                        {{ form.next_date.errors }}
                        <label class="reg-lbl" for="{{ form.next_date.id_for_label }}">Data najbliższego wykonania: </label>
                        {{ form.next_date }}
                    </div>
                    <div class="form-group">
                        {{ form.frequency.errors }}
                        <label class="reg-lbl" for="{{ form.frequency.id_for_label }}">Częstotliwość: </label>
                        <input class="form-control" id="id_frequency" type="number" name="frequency" required="" min="0" /> 
                    </div>
                    <div class="form-group">
                        <label class="reg-lbl" for="type">Typ transakcji:</label>
                        <select class="form-control" value="{{ type }}" name="type" id="type">
                            <option>Wydatek</option>
                            <option>Przychód</option>
                        </select>
                    </div>
                    <button type="submit" class="save btn btn-default">Dodaj</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/index.html
{% extends "base.html" %} {% block title %}Home | Budżet domowy{% endblock %} {% block content %}
{% load static %}
<link href="{% static 'index.css' %}" rel="stylesheet" type="text/css" />


<div id="breadcrumb-panel">   
    <ol class="breadcrumb breadcrumb-arrow">
        <li>
            <a href="/">
                <i class="glyphicon glyphicon-home"></i>
            </a>
        </li>
    </ol>
</div>

<div class="panel-row">
    {% for account in request.session.accounts %}
    <div id="panel-col" class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-3">
                    <img src="{% static "piggy-bank.svg" %}" alt="Piggy bank"/>
                </div>
                <div class="col-xs-9 text-right">
                    <h2>
                        {{ account.name }}
                    </h2>
                    <p>
                        {{ account.balance }} 
                    </p>
                </div>
            </div>
        </div>
        <a href="/konto/{{ account.id }}">
            <div class="panel-footer">
                <div class="row">
                    <span class="pull-left">Zobacz szczegóły</span>
                    <span class="pull-right">
                    <i class="glyphicon glyphicon-circle-arrow-right"></i>
                    </span>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
    <div id="panel-col" class="panel panel-default">
        <div class="panel-body">
            <div class="row add-acc">
                <a href="{% url 'dodanie_konta' %}">
                    <h1 class="glyphicon glyphicon-plus"></h1>
                </a>  
            </div>
        </div>
        
    </div>
</div>

{% endblock %}

mainapp/templates/konto_details.html
{% extends "base.html" %}

{% block title %}Szczegóły skarbonki | Budżet domowy{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'account-details.css' %}" type="text/css"/>
<link rel="stylesheet" href="{% static 'forms.css' %}" type="text/css" />

<div id="breadcrumb-panel">
    <ol class="breadcrumb breadcrumb-arrow">
            <li>
                <a href="/">
                    <i class="glyphicon glyphicon-home"></i>
                </a>
            </li>
            <li><a href="/">Moje skarbonki</a></li>
            <li class="active"><span>{{ current_account.name }}</span></li>
    </ol>
<div id="breadcrumb-panel">

<div class="main-container">
    <div class="container well">
        <div class="row">
            <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Stan skarbonki </h3>
                        </div>
                        <div class="panel-body">
                            <p> {{ current_account.balance }}</p>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Użytkownicy skarbonki </h3>
                        </div>
                        <div class="panel-body">
                            <ul class = "list-group">
                                {% if permissions %}
                                {% for permission in permissions %}
                                    <li class = "list-group-item">
                                        {{ permission.user_id }}<div class="badge">Właściciel</div>
                                    </li>
                                {% endfor %}
                                {% else %}
                                <p>Brak skarbonek</p>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Kategorie </h3>
                        </div>
                        <div class="panel-body">
                            {% if categories %}
                            <ul class = "list-group">
                                {% for category in categories %}
                                    <li class = "list-group-item">
                                        {{ category.name }}
                                        <a href="/usuwanie_kategorii/{{ category.id }}"><span class="pull-right glyphicon glyphicon-minus"></span></a>
                                    </li>
                                {% endfor %}
                            </ul>
                            {% else %}
                            <p>Brak kategorii</p>
                            {% endif %}
                        </div>
                </div>
                <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Dodaj kategorię </h3>
                        </div>
                        <div class="panel-body">
                            <form method="POST" class="category-form">{% csrf_token %} 
                                <div class="form-group">
                                    {{ form.name.errors }}
                                    <label class="reg-lbl" for="{{ form.name.id_for_label }}">Nazwa: </label>
                                    {{ form.name }}
                                </div> 
                                <button type="submit" class="save btn btn-default">Dodaj</button>
                            </form>    
                        </div>
                </div>
                <div class="pull-right">
                    <a href="/usuwanie_konta/{{ current_account.id }}">
                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-minus"></span> Usuń skarbonkę</button>
                </a></div>
            </div>
        </div>  
    </div>
</div>


{% endblock %}